### ISSUE TITLE
Suggestions, Stories and Feed aren't hidden even when I select "Hide"

### ISSUE THREAD

**Issue by em034** [aymyo/antigram-extension#29]
For some time now the Stories were still have been showing up despite me having "Hide Stories" permanently selected. Recently I noticed the Suggestions were also visible again even though I have them permanently selected as "hidden". They stayed visible even when I turned the Hide options off and on again, and refreshed the Instagram page.

Just today I discovered that "Hide Feed" also no longer works. ("Hide Explore" still seems to work for now.)

If someone could fix this soon I'd be very grateful :)

**Comment by aymyo** [comment]
Hi! Thanks a lot for telling me. It looks like Instagram made a lot of changes and broke most of the extension's features. Unfortunately I didn't have time to take care of this until now since I work a fulltime job. But I decided I'm going to focus on it and conviced a friend to help me.

We will try to fix as soon as possible everything that's broken and then improve the extension, we have a lot of ideas :)

Please be patient!

**Comment by em034** [comment]
Thank you! :)
